<a href="https://colab.research.google.com/github/anand-therattil/NaturalLanguageProcessing/blob/main/WordEmbedding.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
from tensorflow.keras.preprocessing.text import one_hot

In [2]:
sent =['the glass of milk',
       'the glass of juice',
       'the cup of tea',
       'I am good boy',
       'I am a bad boy',
       'your videos are ok'
]

In [3]:
sent

['the glass of milk',
 'the glass of juice',
 'the cup of tea',
 'I am good boy',
 'I am a bad boy',
 'your videos are ok']

In [16]:
# Vocabulary Size
voc_size = 10000

In [17]:
onehot_rep = [one_hot(words,voc_size) for words in sent] 

In [18]:
onehot_rep

[[472, 1747, 1890, 8252],
 [472, 1747, 1890, 7697],
 [472, 7567, 1890, 4437],
 [6337, 2686, 3964, 7489],
 [6337, 2686, 4807, 7291, 7489],
 [700, 7880, 9090, 2006]]

In [19]:

from tensorflow.keras.layers import Embedding
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.models import Sequential

In [20]:
import numpy as np 

In [21]:
sent_length =8
embedded_docs = pad_sequences(onehot_rep,padding='pre',maxlen=sent_length)
print(embedded_docs)

[[   0    0    0    0  472 1747 1890 8252]
 [   0    0    0    0  472 1747 1890 7697]
 [   0    0    0    0  472 7567 1890 4437]
 [   0    0    0    0 6337 2686 3964 7489]
 [   0    0    0 6337 2686 4807 7291 7489]
 [   0    0    0    0  700 7880 9090 2006]]


In [22]:
dimesion = 15

In [24]:
model=Sequential()
model.add(Embedding(voc_size,10,input_length=sent_length))
model.compile('adam','mse')

In [25]:
model.summary()

Model: "sequential_1"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 embedding_1 (Embedding)     (None, 8, 10)             100000    
                                                                 
Total params: 100,000
Trainable params: 100,000
Non-trainable params: 0
_________________________________________________________________


In [26]:
print(model.predict(embedded_docs))

1/1 [==============================] - 0s 133ms/step
[[[ 2.41900124e-02 -2.50684619e-02 -6.39278814e-03  1.00928545e-02
    3.62771861e-02 -1.27117410e-02 -3.39011103e-02  3.60901020e-02
    4.23570536e-02  4.38702367e-02]
  [ 2.41900124e-02 -2.50684619e-02 -6.39278814e-03  1.00928545e-02
    3.62771861e-02 -1.27117410e-02 -3.39011103e-02  3.60901020e-02
    4.23570536e-02  4.38702367e-02]
  [ 2.41900124e-02 -2.50684619e-02 -6.39278814e-03  1.00928545e-02
    3.62771861e-02 -1.27117410e-02 -3.39011103e-02  3.60901020e-02
    4.23570536e-02  4.38702367e-02]
  [ 2.41900124e-02 -2.50684619e-02 -6.39278814e-03  1.00928545e-02
    3.62771861e-02 -1.27117410e-02 -3.39011103e-02  3.60901020e-02
    4.23570536e-02  4.38702367e-02]
  [ 3.30952890e-02  1.60499662e-03  1.32571571e-02  2.39939354e-02
   -3.08040865e-02 -1.20826960e-02  4.16631214e-02 -9.32918862e-03
   -4.60487008e-02  4.29405086e-02]
  [-3.33685800e-03 -8.12263414e-03 -3.71407643e-02  1.76377930e-02
    4.74918596e-02  2.90717743

In [33]:
model.predict(embedded_docs[0])

1/1 [==============================] - 0s 17ms/step


array([[ 0.02419001, -0.02506846, -0.00639279,  0.01009285,  0.03627719,
        -0.01271174, -0.03390111,  0.0360901 ,  0.04235705,  0.04387024],
       [ 0.02419001, -0.02506846, -0.00639279,  0.01009285,  0.03627719,
        -0.01271174, -0.03390111,  0.0360901 ,  0.04235705,  0.04387024],
       [ 0.02419001, -0.02506846, -0.00639279,  0.01009285,  0.03627719,
        -0.01271174, -0.03390111,  0.0360901 ,  0.04235705,  0.04387024],
       [ 0.02419001, -0.02506846, -0.00639279,  0.01009285,  0.03627719,
        -0.01271174, -0.03390111,  0.0360901 ,  0.04235705,  0.04387024],
       [ 0.03309529,  0.001605  ,  0.01325716,  0.02399394, -0.03080409,
        -0.0120827 ,  0.04166312, -0.00932919, -0.0460487 ,  0.04294051],
       [-0.00333686, -0.00812263, -0.03714076,  0.01763779,  0.04749186,
         0.02907177,  0.01950273,  0.0242844 ,  0.04394336,  0.0365538 ],
       [ 0.00841957,  0.00825252,  0.04227803,  0.04969538,  0.0420041 ,
         0.01983482, -0.00962152, -0.02461876